// Base de datos oficial de las 65 fórmulas funcionales B2B de NutraSyn Lab
window.productDatabase = [
    // POLVOS - REGISTRO 1: Avena Funcional
    { id: "p1-1", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Relax & Balance", desc: "Bienestar mental, equilibrio diario y relajación funcional.", ingredients: "Harina de Avena, Melena de León, Manzanilla, Cidrón, Passiflora, Canela, Cocoa, Vitamina B6, Vitamina B12, Vitamina C, Bisglicinato de Magnesio", benefits: ["Fuente de fibra y vitaminas", "Ingredientes botánicos funcionales", "Relajación y equilibrio mental"] },
    { id: "p1-2", category: "Nutrición", format: "Polvo", line: "polvos-reg1", name: "Golden Recovery", desc: "Ingredientes botánicos para nutrición y recuperación corporal.", ingredients: "Harina de Avena, Cúrcuma, Pimienta Negra, Colágeno Bovino, Jengibre, Vitamina D, Vitamina C, Bisglicinato de Magnesio", benefits: ["Recuperación física y bienestar", "Con colágeno y antioxidantes", "Soporte óseo y articular"] },
    { id: "p1-3", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Natural Energy", desc: "Activación natural, energía funcional y consumo diario.", ingredients: "Harina de Avena, Remolacha, Espinaca, Yerba Mate, Vitamina C, Guaraná, Vitamina B6, L-Taurina, Vitamina B12", benefits: ["Energía y activación natural", "Soporte metabólico energético", "Superfoods y antioxidantes"] },
    { id: "p1-4", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Green Nutrition", desc: "Nutrición vegetal moderna con ingredientes verdes y enfoque wellness.", ingredients: "Harina de Avena, Proteína de Arveja, Harina de Banano Verde, Camu Camu, Espirulina Verde, Bisglicinato de Magnesio, Vitamina C, Sulfato Ferroso, Vitamina B6", benefits: ["Nutrición vegetal concentrada", "Rica en hierro y minerales", "Ingredientes verdes funcionales"] },
    { id: "p1-5", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Mineral Oat Blend", desc: "Hidratación funcional y reposición de minerales.", ingredients: "Harina de Avena, Limón, Agua de Coco, Citrato de Potasio, Azúcar de Coco, Bisglicinato de Magnesio, Vitamina C, Sal Rosada del Himalaya, Sulfato de Zinc, Cloruro de Sodio, Cloruro de Magnesio, Vitamina B6 (Piridoxina)", benefits: ["Reposición óptima de minerales", "Hidratación profunda", "Minerales y antioxidantes"] },
    { id: "p1-6", category: "Digestivo", format: "Polvo", line: "polvos-reg1", name: "Fiber Balance", desc: "Fibras funcionales y prebióticos para bienestar digestivo.", ingredients: "Harina de Avena, Alcachofa, Inulina, Algarrobo, Yacón, Vinagre de Manzana, Goma Guar, Goma Konjac, Lecitina de Soya, Niacina, Sulfato de Zinc, Vitamina B6 (Piridoxina)", benefits: ["Soporte de la microbiota", "Con fibras funcionales y prebióticos", "Regulación del tránsito intestinal"] },
    { id: "p1-7", category: "Belleza", format: "Polvo", line: "polvos-reg1", name: "Beauty Collagen", desc: "Nutrición funcional premium y tendencias beauty wellness.", ingredients: "Harina de Avena, Colágeno Marino, Péptidos de Colágeno, Arándano, Vitamina C, Bisglicinato de Magnesio, Sulfato de Zinc, Biotina", benefits: ["Nutrición enfocada en la belleza", "Con colágeno marino de alta absorción", "Soporte de piel, cabello y uñas"] },
    { id: "p1-8", category: "Digestivo", format: "Polvo", line: "polvos-reg1", name: "Digestive Fiber", desc: "Fibras y semillas para saciedad y bienestar digestivo.", ingredients: "Harina de Avena, Semilla de Chía, Psyllium, Vitamina C, Bisglicinato de Magnesio, Lecitina de Soya, Vitamina B6, Goma Guar", benefits: ["Alta saciedad digestiva", "Regula el tránsito intestinal", "Semillas y fibras prebióticas"] },
    { id: "p1-9", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Immune Support", desc: "Nutrición diaria y soporte integral funcional.", ingredients: "Harina de Avena, Guayaba, Manzana, Calostro Bovino, Camu Camu, Vitamina C, Vitamina E, Vitamina B6, Vitamina B7, Vitamina D", benefits: ["Soporte al sistema inmunológico", "Antioxidantes y calostro", "Vitaminas esenciales"] },
    { id: "p1-10", category: "Wellness", format: "Polvo", line: "polvos-reg1", name: "Smart Focus", desc: "Claridad mental, enfoque y nutrición funcional moderna.", ingredients: "Harina de Avena, Maca Negra, Levadura Nutricional, Vitamina C, Bisglicinato de Magnesio, Melena de León, Vitamina B3, Vitamina B6, Vitamina B5, Té Blanco", benefits: ["Concentración y enfoque mental", "Adaptógenos de alta calidad", "Vitamina B para energía cognitiva"] },

    // POLVOS - REGISTRO 2: Protein Functional Blend
    { id: "p2-1", category: "Wellness", format: "Polvo", line: "polvos-reg2", name: "Neuro Performance", desc: "Mezcla proteica con ingredientes funcionales para enfoque, claridad mental y rendimiento cognitivo diario.", ingredients: "Proteína Aislada de Soya, Copoazú, Treonato de Magnesio, Azafrán, Vitamina C, Maca Negra, Hongo Chaga, Té Blanco, Vitamina B3, Vitamina B6", benefits: ["Soporte cognitivo activo", "Hongo chaga y adaptógenos", "Proteína de alto valor biológico"] },
    { id: "p2-2", category: "Wellness", format: "Polvo", line: "polvos-reg2", name: "Vital Force", desc: "Frutas funcionales, adaptógenos y extractos vegetales para sensación activa y dinámica.", ingredients: "Proteína Aislada de Soya, Azafrán, Borojó, Chontaduro, Maca, Guaraná, Vitamina C, Vitamina B3, Vitamina B6, Sulfato de Zinc, Selenito de Sodio", benefits: ["Energía y vitalidad física", "Frutas y adaptógenos de la selva", "Metabolismo activo"] },
    { id: "p2-3", category: "Digestivo", format: "Polvo", line: "polvos-reg2", name: "Gut Protein Balance", desc: "Blend proteico con fibras funcionales y prebióticos para bienestar digestivo e intestinal.", ingredients: "Proteína Aislada de Soya, Alcaravea, Inulina, Psyllium, Alcachofa, Fructooligosacáridos (FOS), Harina Konjac, Vinagre de Sidra de Manzana, Bisglicinato de Magnesio, Vitamina B6, Tiamina", benefits: ["Bienestar digestivo avanzado", "Fibras prebióticas y probióticos", "Fácil asimilación proteica"] },
    { id: "p2-4", category: "Wellness", format: "Polvo", line: "polvos-reg2", name: "Green Mineral Blend", desc: "Algas, clorofila y minerales para nutrición verde y micronutrición funcional.", ingredients: "Proteína Aislada de Soya, Espinaca, Espirulina, Chlorella, Vitamina C, Sulfato Ferroso, Alga Marina, Vitamina B6, Vitamina B3, Vitamina B9", benefits: ["Desintoxicación y verdes de alta pureza", "Rico en clorofila y minerales", "Oxigenación celular"] },
    { id: "p2-5", category: "Nutrición", format: "Polvo", line: "polvos-reg2", name: "Amino Muscle Matrix", desc: "Proteína funcional con aminoácidos esenciales para rendimiento nutricional y recuperación muscular.", ingredients: "Proteína Aislada de Soya, Fenogreco, Proteína de Arveja, Vitamina C, L-Taurina, L-Isoleucina, L-Leucina, L-Valina, DL Metionina, Vitamina B3, Vitamina B6", benefits: ["Recuperación muscular rápida", "BCAAs y aminoácidos esenciales", "Soporte de masa muscular"] },
    { id: "p2-6", category: "Belleza", format: "Polvo", line: "polvos-reg2", name: "Beauty Omega Protein", desc: "Concepto de belleza funcional con colágeno, DHA/Omega 3 y antioxidantes para líneas premium wellness.", ingredients: "Proteína Aislada de Soya, Colágeno Hidrolizado, Péptidos de Colágeno, Uva, Vitamina C, Sulfato de Zinc, Ácido Docosahexaenoico (DHA), Ácido Eicosapentaenoico (EPA), Vitamina B3, Vitamina B6, Biotina", benefits: ["Belleza desde el interior", "Omegas esenciales y colágeno", "Protección antioxidante celular"] },
    { id: "p2-7", category: "Nutrición", format: "Polvo", line: "polvos-reg2", name: "Future Protein", desc: "Blend innovador con proteínas alternativas y semillas funcionales orientado a nutrición avanzada y diferenciación comercial.", ingredients: "Proteína Aislada de Soya, Proteína de Arveja, Semilla de Chía, Harina de Grillo, Semilla de Cáñamo, Cacao, Maca, Levadura Nutricional, Vitamina C, Vitamina B3, Vitamina B6", benefits: ["Proteínas alternativas de vanguardia", "Rico en semillas y aminoácidos", "Sostenibilidad e innovación"] },
    { id: "p2-8", category: "Digestivo", format: "Polvo", line: "polvos-reg2", name: "Probiotic Beauty Mix", desc: "Mezcla con probióticos, prebióticos y frutas funcionales para líneas digestivas y bienestar integral femenino.", ingredients: "Proteína Aislada de Soya, Aguaje (Moriche), Inulina, Galactooligosacáridos (GOS), Vitamina C, Lactobacillus Rhamnosus, Pitahaya Amarilla, Pitahaya Rosada, Anís, Menta, Vitamina B3, Vitamina B6", benefits: ["Microbiota y salud digestiva", "Enfoque en salud hormonal femenina", "Fibras de alta asimilación"] },
    { id: "p2-9", category: "Wellness", format: "Polvo", line: "polvos-reg2", name: "Omega Green Fuel", desc: "Concepto funcional con omega 3, cáñamo y matcha enfocado en nutrición moderna y bienestar activo.", ingredients: "Proteína Aislada de Soya, Harina de Cáñamo, Aceite de Linaza, Omega 3, Té Matcha, Vitamina C, Jengibre, Vitamina B3, Vitamina B6, L-Lisina, Bisglicinato de Magnesio", benefits: ["Energía limpia y sostenida", "Omegas vegetales y matcha antioxidante", "Bienestar cardiovascular activo"] },

    // POLVOS - REGISTRO 3: Wellness & Advanced Functional Oats
    { id: "p3-1", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Metabolic Balance", desc: "Fibras y extractos vegetales para equilibrio digestivo y bienestar metabólico.", ingredients: "Harina de Avena, Inulina, Alcachofa, Psyllium, Vinagre de Sidra de Manzana, Té Verde, Vitamina C, Alcaravea, Vitamina E, Picolinato de Cromo, Vitamina D", benefits: ["Control de glucosa y metabolismo", "Fibras de regulación activa", "Soporte metabólico integral"] },
    { id: "p3-2", category: "Nutrición", format: "Polvo", line: "polvos-reg3", name: "Bone & Joint Support", desc: "Colágeno, magnesio y vitaminas para soporte osteomuscular y nutrición estructural.", ingredients: "Harina de Avena, Colágeno Hidrolizado, Citrato de Magnesio, Bisglicinato de Magnesio, Vitamina C, Vitamina K2, Vitamina D3", benefits: ["Fortalecimiento óseo y articular", "Magnesio de alta biodisponibilidad", "Colágeno estructural"] },
    { id: "p3-3", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Active Focus Energy", desc: "Maca, taurina y té verde para energía diaria y enfoque activo.", ingredients: "Harina de Avena, Maca, Remolacha, L-Citrulina Malato, Camu-Camu, Taurina, Vitamina E, Acetil Taurinato de Magnesio, Té Verde, Vitamina D", benefits: ["Enfoque y energía celular", "Aporte antioxidante y de óxido nítrico", "Soporte deportivo diario"] },
    { id: "p3-4", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Neuro Calm Focus", desc: "Treonato de magnesio, Alpha GPC y L-triptófano para bienestar mental y concentración.", ingredients: "Harina de Avena, Melena de León, Treonato de Magnesio, Té Blanco, Vitamina C, Alpha GPC, L-Triptófano, Citrato de Zinc, Vitamina E, Vitamina D", benefits: ["Equilibrio y calma cognitiva", "Treonato de Magnesio para barrera cerebral", "Soporte de neurotransmisores"] },
    { id: "p3-5", category: "Digestivo", format: "Polvo", line: "polvos-reg3", name: "Total Fiber Complex", desc: "Prebióticos y fibras funcionales avanzadas para bienestar digestivo y microbiota.", ingredients: "Harina de Avena, Chía, Nopal, Psyllium, Inulina, Galactooligosacáridos (GOS), Fructooligosacáridos (FOS), Limón, Xilooligosacáridos (XOS), Vitamina C, Vitamina E", benefits: ["Soporte de microbiota avanzado", "Fibras de última generación", "Tránsito digestivo saludable"] },
    { id: "p3-6", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Exotic Energy Blend", desc: "Frutas funcionales y extractos botánicos tropicales para líneas modernas y sensoriales.", ingredients: "Harina de Avena, Lúcuma, Agua de Coco, Borojó, Maca Negra, Galanga, Citrato de Potasio, Guaraná, Vitamina C, Vitamina E, Vitamina B6, Vitamina B12, Vitamina D", benefits: ["Energía e hidratación tropical", "Electrolitos naturales andinos", "Adaptógenos exóticos"] },
    { id: "p3-7", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Immune Mushroom Defense", desc: "Hongos funcionales, beta-glucanos y antioxidantes para bienestar integral.", ingredients: "Harina de Avena, Shiitake, Saúco, Chaga, Beta-Glucanos, Camu Camu, Vitamina C, Vitamina E, Bisglicinato de Zinc, Vitamina D", benefits: ["Soporte inmunitario fúngico", "Beta-glucanos de alta pureza", "Protección antioxidante profunda"] },
    { id: "p3-8", category: "Belleza", format: "Polvo", line: "polvos-reg3", name: "Longevity Beauty Formula", desc: "Resveratrol, colágeno marino y antioxidantes para belleza y bienestar saludable.", ingredients: "Harina de Avena, Colágeno Marino, Acerola (IMP), Resveratrol, Vitamina C (Ácido Ascórbico), Sulfato de Zinc, Seleniometionina (IMP), Vitamina K2, Selenito de Sodio, Vitamina D", benefits: ["Antioxidante celular con resveratrol de alta pureza", "Colágeno marino para elasticidad y firmeza de la piel", "Soporte antiedad con vitaminas y minerales clave"] },
    { id: "p3-9", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Probiotic Fiber Oat", desc: "Avena con maca, cacao y frutas amazónicas para energía y vitalidad natural.", ingredients: "Harina de Avena, Harina de Quinua, Maca, Cacao, Chontaduro, Borojó, Vitamina C (Ácido Ascórbico), Citrato de Magnesio, Vitamina E, Vitamina D", benefits: ["Energía y vitalidad con superfoods amazónicos", "Adaptógenos y antioxidantes naturales", "Perfil sensorial a cacao con frutas exóticas"] },
    { id: "p3-10", category: "Wellness", format: "Polvo", line: "polvos-reg3", name: "Premium Neuro Adapt", desc: "Adaptógenos y compuestos funcionales avanzados para líneas premium de enfoque y rendimiento mental.", ingredients: "Harina de Avena, Copoazú, Vitamina C (Ácido Ascórbico), Té Blanco, Vitamina E, Alpha GPC (Alpha Colina GPC) (IMP), Treonato de Magnesio, Acetil Taurinato de Magnesio (IMP), Azafrán, Vitamina B6 (Piridoxina HCl), Vitamina B9 (Ácido Fólico / Metilfolato), Vitamina B12 (Metilcobalamina), Vitamina D", benefits: ["Claridad mental y enfoque con nootrópicos", "Magnesio neuro-específico de alta absorción", "Antioxidantes y complejo B para energía cognitiva"] },

    // POLVOS - REGISTRO 4: Instant Functional Mixes
    { id: "p4-1", category: "Wellness", format: "Polvo", line: "polvos-reg4", name: "Relax Coconut Mix", desc: "Mezcla cremosa con magnesio y extractos herbales para bienestar y relajación diaria.", ingredients: "Maltodextrina, Fécula de Maíz, Bisglicinato de Magnesio, Cidrón, Manzanilla, Leche de Coco, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Relajación y bienestar nervioso diario", "Magnesio de alta biodisponibilidad", "Textura cremosa a coco con notas herbales"] },
    { id: "p4-2", category: "Nutrición", format: "Polvo", line: "polvos-reg4", name: "Protein Cocoa Shake", desc: "Concepto proteico chocolate con suero de leche y banano para nutrición práctica.", ingredients: "Maltodextrina, Fécula de Maíz, Proteína Concentrada de Suero 35%, Proteína Concentrada de Suero 70%, Cocoa, Lecitina de Soya, Banano, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Aporte proteico de alto valor biológico", "Perfil chocolate cremoso y práctico", "Ideal para recuperación y nutrición diaria"] },
    { id: "p4-3", category: "Digestivo", format: "Polvo", line: "polvos-reg4", name: "Digestive Probiotic Blend", desc: "Prebióticos, probióticos y extractos herbales para bienestar digestivo integral.", ingredients: "Maltodextrina, Fécula de Maíz, Inulina, Menta, Manzanilla, Probióticos (Bacillus coagulans), Anís, Jengibre, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Prebióticos y probióticos para la microbiota", "Confort digestivo con hierbas tradicionales", "Fácil disolución y perfil suave"] },
    { id: "p4-4", category: "Digestivo", format: "Polvo", line: "polvos-reg4", name: "Immune Gut Support", desc: "FOS, aloe vera y calostro bovino para bienestar integral y soporte nutricional.", ingredients: "Maltodextrina, Fécula de Maíz, Fructooligosacáridos (FOS), Aloe Vera, Calostro Bovino, Sulfato de Zinc, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Soporte inmunológico y digestivo combinado", "FOS prebiótico y calostro bovino", "Aloe vera para confort gastrointestinal"] },
    { id: "p4-5", category: "Wellness", format: "Polvo", line: "polvos-reg4", name: "Fruit Wellness Drink", desc: "Mezcla frutal refrescante con ingredientes vegetales para hidratación y bienestar cotidiano.", ingredients: "Maltodextrina, Fécula de Maíz, Hinojo, Frambuesa, Piña, Cidrón, Vitamina C (Ácido Ascórbico), Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Hidratación refrescante con frutas naturales", "Vitamina C para apoyo inmunológico diario", "Perfil frutal ligero y agradable"] },
    { id: "p4-6", category: "Wellness", format: "Polvo", line: "polvos-reg4", name: "Golden Spice Mix", desc: "Cúrcuma, jengibre y pimientas para conceptos cálidos y funcionales de alta aceptación.", ingredients: "Maltodextrina, Fécula de Maíz, Naranja, Cúrcuma, Jengibre, Vitamina C (Ácido Ascórbico), Pimienta Cayena, Pimienta Negra, Miel, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Perfil cálido y antioxidante con cúrcuma", "Piperina natural para mejor absorción", "Alta aceptación sensorial y versatilidad"] },
    { id: "p4-7", category: "Digestivo", format: "Polvo", line: "polvos-reg4", name: "Green Detox Nutrition", desc: "Concepto vegetal premium con superfoods, algas y vegetales funcionales para líneas verdes y wellness.", ingredients: "Maltodextrina, Fécula de Maíz, Piña, Apio, Espinaca, Remolacha, Zanahoria, Alfalfa, Espirulina, Goji, Chlorella, Açaí, Saúco, Moringa, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina)", benefits: ["Superfoods verdes y algas depurativas", "Alcalinización y aporte de clorofila natural", "Antioxidantes de frutas y vegetales funcionales"] },
    { id: "p4-8", category: "Belleza", format: "Polvo", line: "polvos-reg4", name: "Beauty Antioxidant Complex", desc: "Mezcla funcional con colágeno, antioxidantes y minerales asociada a belleza y nutrición avanzada.", ingredients: "Maltodextrina, Fécula de Maíz, Colágeno Hidrolizado, Uva, Romero, Sulfato de Zinc, Selenito de Sodio, Vitamina B12 (Cobalamina), Vitamina B3 (Niacina), Vitamina B6 (Piridoxina), Vitamina B8 (Biotina)", benefits: ["Colágeno y antioxidantes para belleza integral", "Minerales clave para piel, cabello y uñas", "Polifenoles de uva y romero"] },
    { id: "p4-9", category: "Nutrición", format: "Polvo", line: "polvos-reg4", name: "Vital Men Nutrition", desc: "Concepto funcional masculino con semillas, antioxidantes y micronutrientes para bienestar activo.", ingredients: "Maltodextrina, Fécula de Maíz, Tomate, Arándano, Maca, Semillas de Calabaza, Vitamina C (Ácido Ascórbico), Vitamina B6 (Piridoxina), Vitamina B3 (Niacina), Sulfato de Zinc, Selenito de Sodio, Vitamina D, Vitamina E, Vitamina B12 (Cobalamina)", benefits: ["Micronutrientes clave para vitalidad masculina", "Antioxidantes de tomate y arándano", "Zinc y selenio para bienestar activo"] },

    // LÍQUIDOS - REGISTRO 1: Bebidas Funcionales Básicas
    { id: "l1-1", category: "Nutrición", format: "Líquido", line: "liquidos-reg1", name: "Golden Recovery", desc: "Bebida inspirada en ingredientes tradicionalmente utilizados en bienestar físico y recuperación diaria. Combina proteínas, extractos vegetales y vitamina C en un perfil cítrico y refrescante.", ingredients: "Colágeno Hidrolizado, Cúrcuma, Jengibre, Pimienta Negra, Vitamina C (Ácido Ascórbico), Vitamina B6 (Piridoxina), Vitamina D, Vitamina B12 (Cobalamina)", benefits: ["Recuperación física con colágeno hidrolizado", "Cúrcuma y jengibre antioxidantes", "Vitamina C y B12 para energía diaria"] },
    { id: "l1-2", category: "Wellness", format: "Líquido", line: "liquidos-reg1", name: "Solar Tropical Hydration", desc: "Bebida de hidratación con perfil tropical, formulada con frutas y electrolitos para acompañar la reposición diaria de líquidos y minerales. Ideal para estilos de vida activos.", ingredients: "Sandía, Maracuyá, Limón, Coco, Vitamina C, Cloruro de Sodio, Citrato de Potasio", benefits: ["Hidratación tropical con electrolitos naturales", "Frutas frescas ricas en vitamina C", "Ideal para estilos de vida activos"] },
    { id: "l1-3", category: "Wellness", format: "Líquido", line: "liquidos-reg1", name: "Night Harmony", desc: "Bebida de consumo nocturno con ingredientes tradicionalmente utilizados para promover momentos de relajación y bienestar antes del descanso. Perfil suave y refrescante.", ingredients: "Manzanilla, Menta, Bisglicinato de Magnesio, Passiflora, Cidrón, Miel", benefits: ["Relajación nocturna con botánicos tradicionales", "Magnesio de alta absorción para calma muscular", "Perfil suave ideal antes del descanso"] },
    { id: "l1-4", category: "Belleza", format: "Líquido", line: "liquidos-reg1", name: "Beauty Collagen Drink", desc: "Bebida con colágeno y antioxidantes, desarrollada para líneas de belleza desde la nutrición. Combina proteínas, vitaminas y frutas con un perfil premium.", ingredients: "Péptidos de Colágeno, Colágeno Marino, Arándano, Vitamina C (Ácido Ascórbico), Vitamina B6 (Piridoxina), Vitamina B12 (Cobalamina), Citrato de Zinc, Vitamina E, Vitamina B8 (Biotina)", benefits: ["Doble fuente de colágeno para piel y cabello", "Antioxidantes de arándano de alta pureza", "Vitaminas clave de belleza en perfil premium"] },
    { id: "l1-5", category: "Digestivo", format: "Líquido", line: "liquidos-reg1", name: "Digest Reset", desc: "Bebida con fibras e ingredientes de origen vegetal utilizada como complemento de una alimentación enfocada en el bienestar digestivo y el consumo de fibra.", ingredients: "Inulina, Aloe Vera, Alcachofa, Jengibre, Anís, Menta", benefits: ["Fibra prebiótica para la microbiota", "Alcachofa y aloe vera para confort digestivo", "Perfil herbal suave y digestivo"] },
    { id: "l1-6", category: "Belleza", format: "Líquido", line: "liquidos-reg1", name: "Pink Paradise Beauty", desc: "Bebida de frutas y colágeno diseñada para líneas beauty, con ingredientes antioxidantes y vitaminas que complementan un estilo de vida saludable.", ingredients: "Sandía, Pitahaya, Colágeno Marino, Uva, Arándano, Vitamina C, Vitamina B8 (Biotina)", benefits: ["Colágeno marino y frutos rojos antioxidantes", "Biotina para piel, cabello y uñas", "Perfil frutal ligero y refrescante"] },
    { id: "l1-7", category: "Digestivo", format: "Líquido", line: "liquidos-reg1", name: "Green Daily", desc: "Mezcla líquida de vegetales verdes, frutas y superalimentos para complementar la alimentación diaria con ingredientes de origen vegetal.", ingredients: "Piña, Aloe Vera, Espinaca, Limón, Clorofila, Moringa, Espirulina Azul", benefits: ["Vegetales verdes y superalimentos concentrados", "Clorofila y espirulina azul antioxidante", "Aporte diario de nutrientes vegetales"] },
    { id: "l1-8", category: "Wellness", format: "Líquido", line: "liquidos-reg1", name: "Golden Immunity Shot", desc: "Shot funcional con cítricos, extractos vegetales y vitaminas, desarrollado para líneas enfocadas en nutrición diaria y bienestar general.", ingredients: "Naranja, Cúrcuma, Jengibre, Propóleo, Vitamina C, Sulfato de Zinc, Beta-Glucanos de Ganoderma, Miel, Vitamina D", benefits: ["Shot cítrico concentrado en vitamina C", "Propóleo y beta-glucanos para las defensas", "Cúrcuma y jengibre antioxidante natural"] },
    { id: "l1-9", category: "Digestivo", format: "Líquido", line: "liquidos-reg1", name: "Green Detox", desc: "Bebida verde con vegetales y clorofila, ideal para líneas wellness y consumidores que buscan incorporar ingredientes vegetales en su alimentación diaria.", ingredients: "Clorofila, Espirulina, Espinaca", benefits: ["Clorofila y espirulina depurativas", "Alcalinización natural del organismo", "Fórmula simple y concentrada"] },

    // LÍQUIDOS - REGISTRO 2: Línea de Bebidas Premium
    { id: "l2-1", category: "Nutrición", format: "Líquido", line: "liquidos-reg2", name: "Functional Collagen", desc: "Bebida funcional con colágeno y magnesio inspirada en consumidores que buscan una alternativa práctica para complementar su rutina diaria con proteína y minerales.", ingredients: "Colágeno Hidrolizado, Citrato de Magnesio, Vitamina C (Ácido Ascórbico), Vitamina D3, Vitamina K2, Bisglicinato de Magnesio", benefits: ["Colágeno funcional de fácil consumo diario", "Doble fuente de magnesio de alta absorción", "Vitamina D3 y K2 para salud ósea"] },
    { id: "l2-2", category: "Nutrición", format: "Líquido", line: "liquidos-reg2", name: "Sacha Protein Coffee", desc: "Bebida premium que combina proteína, café y Sacha Inchi para ofrecer una experiencia funcional con perfil moka, ideal para líneas de nutrición activa y proteína lista para consumir.", ingredients: "Sacha Inchi, Caseinato de Calcio, Café Liofilizado, Cacao, Proteína WPI90, L-Taurina, Maca", benefits: ["Proteína premium lista para consumir", "Perfil moka con Sacha Inchi y café", "Taurina y maca para energía activa"] },
    { id: "l2-3", category: "Wellness", format: "Líquido", line: "liquidos-reg2", name: "Focus Drink", desc: "Bebida tropical con frutas amazónicas, extractos vegetales y vitaminas, diseñada para consumidores que buscan energía limpia y una nutrición práctica para el día a día.", ingredients: "Borojó, Azafrán, Maracuyá, Chontaduro, Guaraná, Maca, Taurina, Vitamina C (Ácido Ascórbico), Vitamina D, Vitamina E", benefits: ["Energía limpia con frutas amazónicas", "Azafrán y guaraná para enfoque natural", "Vitaminas para nutrición práctica diaria"] },
    { id: "l2-4", category: "Digestivo", format: "Líquido", line: "liquidos-reg2", name: "Tropical Fiber Light", desc: "Bebida ligera con fibra e ingredientes de origen vegetal, formulada para complementar una alimentación rica en fibra con un agradable perfil tropical.", ingredients: "Ciruela, Inulina, Aloe Vera, Piña, Papaya, Mango, Pectina Cítrica", benefits: ["Fibra soluble de origen frutal y vegetal", "Enzimas naturales de papaya y piña", "Perfil tropical ligero y refrescante"] },
    { id: "l2-5", category: "Wellness", format: "Líquido", line: "liquidos-reg2", name: "Golden Active Shot", desc: "Shot funcional con cúrcuma, jengibre y cítricos, desarrollado para líneas wellness con ingredientes tradicionalmente utilizados en nutrición diaria y estilos de vida activos.", ingredients: "Naranja, Cúrcuma, Jengibre, Vitamina C (Ácido Ascórbico), Pimienta Cayena, Pimienta Negra, Miel, Vitamina B3 (Niacina), Vitamina B6 (Piridoxina), Vitamina B12 (Cobalamina)", benefits: ["Shot cítrico y picante estimulante", "Cúrcuma y jengibre de alta biodisponibilidad", "Vitaminas B para energía activa"] },
    { id: "l2-6", category: "Belleza", format: "Líquido", line: "liquidos-reg2", name: "Beauty Collagen Berry", desc: "Bebida premium de colágeno marino, péptidos y frutos rojos, desarrollada para líneas de belleza desde la nutrición con un perfil sofisticado y de alto valor agregado.", ingredients: "Colágeno Marino, Uva, Péptidos de Colágeno, Arándano, Vitamina C, Zinc Metionina, Vitamina E, Biotina", benefits: ["Colágeno marino premium con péptidos", "Frutos rojos antioxidantes de alto valor", "Zinc y biotina para belleza integral"] },
    { id: "l2-7", category: "Nutrición", format: "Líquido", line: "liquidos-reg2", name: "Tomato Vital", desc: "Bebida antioxidante con tomate, arándano y vitaminas, diseñada para consumidores que buscan incorporar ingredientes vegetales y antioxidantes en su alimentación diaria.", ingredients: "Tomate, Arándano, Maca, Sulfato de Zinc, Vitamina C (Ácido Ascórbico), Vitamina B3 (Niacina), Vitamina E, Vitamina B6 (Piridoxina), Vitamina B12 (Cobalamina), Vitamina D", benefits: ["Licopeno de tomate y antioxidantes frutales", "Zinc y vitaminas del complejo B", "Ingredientes vegetales de alimentación diaria"] },
    { id: "l2-8", category: "Belleza", format: "Líquido", line: "liquidos-reg2", name: "Red Antiox", desc: "Bebida con uva, arándano, resveratrol y vitaminas antioxidantes, ideal para líneas premium enfocadas en nutrición funcional y bienestar diario.", ingredients: "Uva, Colágeno Hidrolizado, Manzana, Resveratrol, Vitamina C (Ácido Ascórbico), Vitamina B3 (Niacina), Vitamina E, Vitamina B6 (Piridoxina), Vitamina B12 (Cobalamina)", benefits: ["Resveratrol premium antiedad", "Colágeno y antioxidantes de frutos rojos", "Perfil funcional para bienestar diario"] },
    { id: "l2-9", category: "Wellness", format: "Líquido", line: "liquidos-reg2", name: "Golden Amazon Energy", desc: "Bebida inspirada en ingredientes amazónicos como maca, guaraná y frutas tropicales, desarrollada para consumidores que buscan energía y nutrición funcional en un solo producto.", ingredients: "Uva, Limón, Maca, Guaraná, L-Taurina, Té Verde, Goma Acacia, Vitamina B3, Vitamina B6", benefits: ["Energía amazónica con maca y guaraná", "Té verde y taurina para rendimiento", "Nutrición funcional en un solo producto"] },

    // LÍQUIDOS - REGISTRO 3: Functional Liquid Shots
    { id: "l3-1", category: "Wellness", format: "Líquido", line: "liquidos-reg3", name: "Ginger Fire Shot", desc: "Shot funcional desarrollado para apoyar las defensas naturales, aportar antioxidantes y complementar un estilo de vida activo, con acción antiinflamatoria natural.", ingredients: "Naranja, Cúrcuma, Jengibre, Vitamina C, Pimienta Negra, Pimienta Cayena, Citrato de Magnesio, Miel", benefits: ["Shot antiinflamatorio con cúrcuma y jengibre", "Vitamina C y magnesio de rápida absorción", "Estímulo natural para el sistema inmune"] },
    { id: "l3-2", category: "Wellness", format: "Líquido", line: "liquidos-reg3", name: "Neuro Calm", desc: "Bebida funcional diseñada para favorecer la relajación, la calma mental y el bienestar del sistema nervioso.", ingredients: "Manzanilla, Cidrón, Cilantro, Té Blanco, Treonato de Magnesio, Vitamina B6, Vitamina B12", benefits: ["Calma mental con botánicos tradicionales", "Treonato de magnesio neuro-específico", "Vitaminas B para el sistema nervioso"] },
    { id: "l3-3", category: "Wellness", format: "Líquido", line: "liquidos-reg3", name: "Immune Shield", desc: "Bebida funcional rica en antioxidantes, vitaminas y extractos vegetales para complementar la nutrición diaria.", ingredients: "Saúco, Propóleo, Jengibre, Vitamina C, Marañón, Sulfato de Zinc, Vitamina D, Chaga", benefits: ["Propóleo y saúco para las defensas", "Antioxidantes de marañón y chaga", "Vitamina C y D en perfil inmune completo"] },
    { id: "l3-4", category: "Wellness", format: "Líquido", line: "liquidos-reg3", name: "Cardio Crimson", desc: "Bebida funcional con frutas, extractos vegetales y antioxidantes orientada al bienestar cardiovascular.", ingredients: "Uva, Flor de Jamaica (Hibiscus), Jengibre, Sacha Inchi, Ajo, Resveratrol, Citrato de Potasio, Citrato de Magnesio, L-Taurina, Vitamina C (Ácido Ascórbico), Vitamina E, Remolacha", benefits: ["Antioxidantes para bienestar cardiovascular", "Ajo y resveratrol de acción vascular", "Electrolitos y vitamina E complementarios"] },
    { id: "l3-5", category: "Digestivo", format: "Líquido", line: "liquidos-reg3", name: "Liver Reset", desc: "Bebida funcional elaborada con extractos botánicos tradicionalmente utilizados para favorecer la función digestiva y el bienestar hepático.", ingredients: "Alcachofa, Aloe Vera, Limón, Jengibre, Menta, Clorofila, Té Verde, Citrato de Potasio, Vitamina C", benefits: ["Alcachofa y clorofila para función hepática", "Botánicos digestivos tradicionales", "Perfil detox refrescante"] },
    { id: "l3-6", category: "Digestivo", format: "Líquido", line: "liquidos-reg3", name: "Metabolic Fire", desc: "Bebida funcional desarrollada para complementar programas de control de peso y hábitos de alimentación saludable.", ingredients: "Vinagre de Manzana, Inulina, Té Verde, Nopal, Jengibre, Maracuyá, Canela, Citrato de Magnesio", benefits: ["Vinagre de manzana y té verde metabólico", "Fibra prebiótica de inulina y nopal", "Apoyo a hábitos de control de peso"] },
    { id: "l3-7", category: "Digestivo", format: "Líquido", line: "liquidos-reg3", name: "Green Detox", desc: "Bebida funcional con vegetales, frutas tropicales y fibra prebiótica para complementar el bienestar digestivo.", ingredients: "Aloe Vera, Inulina, Piña, Espinaca, Pepino, Menta, Té Verde, Clorofila", benefits: ["Vegetales verdes y fibra prebiótica", "Piña y pepino para hidratación digestiva", "Clorofila depurativa natural"] },
    { id: "l3-8", category: "Wellness", format: "Líquido", line: "liquidos-reg3", name: "Tropical Energy", desc: "Bebida funcional energizante formulada con frutas tropicales, guaraná, taurina y vitaminas del complejo B.", ingredients: "Piña, Chontaduro, Guaraná, L-Taurina, Vitamina B6 (Piridoxina), Vitamina B3 (Niacina), Vitamina B12 (Cobalamina)", benefits: ["Energía tropical con guaraná y taurina", "Frutas amazónicas energizantes", "Vitaminas B para rendimiento físico"] },
    { id: "l3-9", category: "Nutrición", format: "Líquido", line: "liquidos-reg3", name: "Cherry Vital Boost", desc: "Bebida funcional con frutas, vitaminas y minerales diseñada para acompañar un estilo de vida activo.", ingredients: "Extracto de Malta, Guayaba, Maca, Vitamina C, Aminoácidos de Soya, Vitamina B3 (Niacina), Vitamina E, Sulfato de Zinc, Sulfato Ferroso, Vitamina A, Vitamina B5 (Ácido Pantoténico), Vitamina B1 (Tiamina), Vitamina B6 (Piridoxina), Vitamina B2 (Riboflavina), Vitamina B12 (Cobalamina)", benefits: ["Complejo multivitamínico completo", "Minerales esenciales para energía diaria", "Maca y guayaba para vitalidad activa"] }
];

// Nombres descriptivos de las líneas de registro sanitario
window.lineNamesMap = {
    "polvos-reg1": "Polvos Reg. 1 - Avena Funcional & Superalimentos",
    "polvos-reg2": "Polvos Reg. 2 - Protein Blend Matrix & Neuro",
    "polvos-reg3": "Polvos Reg. 3 - Wellness & Advanced Functional Oats",
    "polvos-reg4": "Polvos Reg. 4 - Instant Mixes Solubles",
    "liquidos-reg1": "Líquidos Reg. 1 - Bebidas Funcionales Básicas",
    "liquidos-reg2": "Líquidos Reg. 2 - Elixires Concentrados Bioactivos",
    "liquidos-reg3": "Líquidos Reg. 3 - Bebidas Funcionales de Bienestar Integral"
};
