// Catálogo real de ingredientes de costeo del negocio (códigos IN001–IN286),
// tal como lo entregó el usuario — no son códigos inventados por el sistema.
// El "nombre" aquí es el nombre INTERNO/técnico completo (puede incluir
// anotaciones de formato/origen como "en Polvo", "en Liquido (WOH)", "(IMP)",
// "(AMPES)", "(APMES)", "(NoInvimagil)"). Esas anotaciones NO se le muestran
// al cliente en las cotizaciones — se limpian en el momento de mostrarlas
// (ver cleanIngredientDisplay() en cotizaciones.html), no aquí: este archivo
// guarda el registro completo tal cual, por si el colaborador necesita
// verlo/buscarlo con el detalle técnico.
export const DEFAULT_INGREDIENTS = [
  { code: "IN001", nombre: "Chaga en Polvo" },
  { code: "IN002", nombre: "Champiñon en polvo - Agaricus Bisporus (IMP)" },
  { code: "IN003", nombre: "Hongo Reishi en Polvo (AMPES)" },
  { code: "IN004", nombre: "Hongo Shiitake en Polvo" },
  { code: "IN005", nombre: "Acido Citrico" },
  { code: "IN006", nombre: "Dioxido de Silicio" },
  { code: "IN007", nombre: "Fosfato Tricálcico" },
  { code: "IN008", nombre: "Goma Acacia" },
  { code: "IN009", nombre: "Goma Guar" },
  { code: "IN010", nombre: "Goma Xhantan" },
  { code: "IN011", nombre: "Lecitina de Soya" },
  { code: "IN012", nombre: "Pectina Cítrica Rápida" },
  { code: "IN013", nombre: "DL Metionina" },
  { code: "IN014", nombre: "L-Arginina (AMPES)" },
  { code: "IN015", nombre: "L-Histidina" },
  { code: "IN016", nombre: "L-Isoleucina" },
  { code: "IN017", nombre: "L-Leucina" },
  { code: "IN018", nombre: "L-Lisina" },
  { code: "IN019", nombre: "L-Treonina" },
  { code: "IN020", nombre: "L-Valina" },
  { code: "IN021", nombre: "Metionina + Cisteina" },
  { code: "IN022", nombre: "Acerola en Polvo (IMP)" },
  { code: "IN023", nombre: "Arándano en Polvo" },
  { code: "IN024", nombre: "Azafrán en Polvo" },
  { code: "IN025", nombre: "Camu Camu en Polvo" },
  { code: "IN026", nombre: "Coenzima Q10 (CoQ10) en Polvo (APMES)" },
  { code: "IN027", nombre: "Cúrcuma en Polvo" },
  { code: "IN028", nombre: "Goji en Polvo" },
  { code: "IN029", nombre: "Granada en Polvo" },
  { code: "IN030", nombre: "Mangostino en Polvo" },
  { code: "IN031", nombre: "Resveratrol en Polvo" },
  { code: "IN032", nombre: "Romero en Polvo" },
  { code: "IN033", nombre: "Té Blanco en Polvo" },
  { code: "IN034", nombre: "Té Verde en Polvo" },
  { code: "IN035", nombre: "Uchuva en Polvo" },
  { code: "IN036", nombre: "Uva en Polvo" },
  { code: "IN037", nombre: "Algarrobo en Polvo" },
  { code: "IN038", nombre: "Crema no Lactea en Polvo" },
  { code: "IN039", nombre: "Extracto de Malta en Polvo" },
  { code: "IN040", nombre: "Fécula de Maíz" },
  { code: "IN041", nombre: "Harina de Arroz" },
  { code: "IN042", nombre: "Harina de Avena" },
  { code: "IN043", nombre: "Leche de Coco en Polvo" },
  { code: "IN044", nombre: "Maltodextrina 17-20" },
  { code: "IN045", nombre: "Maltodextrina 18-20" },
  { code: "IN046", nombre: "Suero de Leche en Polvo" },
  { code: "IN047", nombre: "Ácido Hialurónico en Polvo (AMPES)" },
  { code: "IN048", nombre: "Colágeno Hidrolizado" },
  { code: "IN049", nombre: "Colágeno Marino" },
  { code: "IN050", nombre: "Péptidos de Colágeno" },
  { code: "IN051", nombre: "Alpha GPC (Alpha Colina GPC) (IMP)" },
  { code: "IN052", nombre: "Bitartrato de Colina (APMES)" },
  { code: "IN053", nombre: "Cloruro de Colina (APMES)" },
  { code: "IN054", nombre: "Fenilalanina + Tirosina" },
  { code: "IN055", nombre: "Inositol (AMPES)" },
  { code: "IN056", nombre: "Melena de León en Polvo" },
  { code: "IN057", nombre: "Treonato de Magnesio" },
  { code: "IN058", nombre: "Color Naranja en Polvo" },
  { code: "IN059", nombre: "Color Rojo en Polvo" },
  { code: "IN060", nombre: "Benzoato de Sodio" },
  { code: "IN061", nombre: "Sorbato de Potasio" },
  { code: "IN062", nombre: "Beta-Alanina en Polvo (APMES)" },
  { code: "IN063", nombre: "Creatina Monohidratada en Polvo (AMPES)" },
  { code: "IN064", nombre: "Ecdysterona en Polvo (AMPES)" },
  { code: "IN065", nombre: "Glutamina en Polvo (APMES)" },
  { code: "IN066", nombre: "L-Carnitina (APMES)" },
  { code: "IN067", nombre: "Pimienta Cayena en Polvo" },
  { code: "IN068", nombre: "Remolacha en Polvo" },
  { code: "IN069", nombre: "Alcachofa en Polvo" },
  { code: "IN070", nombre: "Alcaravea en Polvo" },
  { code: "IN071", nombre: "Aloe vera en Polvo" },
  { code: "IN072", nombre: "Anís en Polvo" },
  { code: "IN073", nombre: "Cardo Mariano en Polvo (NoInvimagil)" },
  { code: "IN074", nombre: "Ciruela en Polvo" },
  { code: "IN075", nombre: "Galanga en Polvo (IMP)" },
  { code: "IN076", nombre: "Hinojo en Polvo" },
  { code: "IN077", nombre: "Jengibre en Polvo" },
  { code: "IN078", nombre: "Menta en Polvo" },
  { code: "IN079", nombre: "Nopal en Polvo" },
  { code: "IN080", nombre: "Papaya en Polvo" },
  { code: "IN081", nombre: "Pimienta Negra en Polvo" },
  { code: "IN082", nombre: "Piña en Polvo" },
  { code: "IN083", nombre: "Vinagre de Manzana en Polvo" },
  { code: "IN084", nombre: "Agua de Coco en Polvo" },
  { code: "IN085", nombre: "Citrato de Potasio" },
  { code: "IN086", nombre: "Citrato de Sodio" },
  { code: "IN087", nombre: "Cloruro de Potasio" },
  { code: "IN088", nombre: "Cloruro de Sodio" },
  { code: "IN089", nombre: "Sal Rosada del Himalaya" },
  { code: "IN090", nombre: "Azúcar de Coco" },
  { code: "IN091", nombre: "Estevia en Polvo" },
  { code: "IN092", nombre: "Fructosa en Polvo" },
  { code: "IN093", nombre: "Miel en Polvo" },
  { code: "IN094", nombre: "Sucralosa en Polvo" },
  { code: "IN095", nombre: "Borojo en Polvo" },
  { code: "IN096", nombre: "Café Liofilizado en Polvo" },
  { code: "IN097", nombre: "Cafeína Anhidra" },
  { code: "IN098", nombre: "Chontaduro en Polvo" },
  { code: "IN099", nombre: "Guaraná en Polvo" },
  { code: "IN100", nombre: "L-Taurina en Polvo" },
  { code: "IN101", nombre: "Maca Amarilla en Polvo" },
  { code: "IN102", nombre: "Maca Negra en Polvo" },
  { code: "IN103", nombre: "Té Matcha en Polvo" },
  { code: "IN104", nombre: "Yerba Mate" },
  { code: "IN105", nombre: "Fructooligosacáridos (FOS) en Polvo" },
  { code: "IN106", nombre: "Galactooligosacáridos (GOS) en Polvo" },
  { code: "IN107", nombre: "Goma Konjac" },
  { code: "IN108", nombre: "Harina de Banano Verde en Polvo" },
  { code: "IN109", nombre: "Harina de Coco" },
  { code: "IN110", nombre: "Inulina" },
  { code: "IN111", nombre: "Polidextrosa" },
  { code: "IN112", nombre: "Psyllium en Polvo" },
  { code: "IN113", nombre: "Salvado de Avena" },
  { code: "IN114", nombre: "Salvado de Trigo" },
  { code: "IN115", nombre: "Xilooligosacáridos (XOS) (IMP)" },
  { code: "IN116", nombre: "Yacón en Polvo" },
  { code: "IN117", nombre: "Banano en Polvo" },
  { code: "IN118", nombre: "Frambuesa en Polvo" },
  { code: "IN119", nombre: "Guayaba en Polvo" },
  { code: "IN120", nombre: "Manzana Verde en Polvo" },
  { code: "IN121", nombre: "Maracuyá en Polvo" },
  { code: "IN122", nombre: "Mora en Polvo" },
  { code: "IN123", nombre: "Naranja en Polvo" },
  { code: "IN124", nombre: "Pitahaya Amarilla en Polvo" },
  { code: "IN125", nombre: "Pitahaya Rosada en Polvo" },
  { code: "IN126", nombre: "Aceite de Almendras en Polvo" },
  { code: "IN127", nombre: "Aceite de Linaza en Polvo" },
  { code: "IN128", nombre: "DHA Resistant (DHA + EPA)" },
  { code: "IN129", nombre: "Omega 3 en Polvo" },
  { code: "IN130", nombre: "Semilla de Cáñamo/Hemp" },
  { code: "IN131", nombre: "Semilla de Chía en Polvo" },
  { code: "IN132", nombre: "Semilla de Chía Entera" },
  { code: "IN133", nombre: "Semillas de Calabaza en Polvo" },
  { code: "IN134", nombre: "Beta-Glucanos de Ganoderma en Polvo" },
  { code: "IN135", nombre: "Sauco en Polvo" },
  { code: "IN136", nombre: "Acetil Taurinato de Magnesio (IMP)" },
  { code: "IN137", nombre: "Bisglicinato de Magnesio" },
  { code: "IN138", nombre: "Bisglicinato de Zinc" },
  { code: "IN139", nombre: "Bisglicinato Ferroso" },
  { code: "IN140", nombre: "Carbonato de Calcio" },
  { code: "IN141", nombre: "Citrato de Calcio" },
  { code: "IN142", nombre: "Citrato de Magnesio" },
  { code: "IN143", nombre: "Glicinato Ferrico" },
  { code: "IN144", nombre: "Malato de Magnesio (IMP)" },
  { code: "IN145", nombre: "Picolinato de Cromo" },
  { code: "IN146", nombre: "Seleniometionina (IMP)" },
  { code: "IN147", nombre: "Selenito de Sodio" },
  { code: "IN148", nombre: "Sulfato de Zinc" },
  { code: "IN149", nombre: "Sulfato Ferroso" },
  { code: "IN150", nombre: "Yoduro de Potasio" },
  { code: "IN151", nombre: "Zinc Metionina (IMP)" },
  { code: "IN152", nombre: "Probióticos (Bacillus Coagulans)" },
  { code: "IN153", nombre: "Probióticos (Lactobacillus Rhamnosus)" },
  { code: "IN154", nombre: "Albúmina de Huevo" },
  { code: "IN155", nombre: "Calostro Bovino en Polvo" },
  { code: "IN156", nombre: "Caseinato de Calcio" },
  { code: "IN157", nombre: "Caseinato de Magnesio" },
  { code: "IN158", nombre: "Harina de Cáñamo/Hemp" },
  { code: "IN159", nombre: "Harina de Grillo en Polvo" },
  { code: "IN160", nombre: "Harina de Sacha Inchi" },
  { code: "IN161", nombre: "Lupino en Polvo (IMP)" },
  { code: "IN162", nombre: "Proteína Aislada de Soya (Aislada 90%)" },
  { code: "IN163", nombre: "Proteína Aislada de Suero 90% (WPI90)" },
  { code: "IN164", nombre: "Proteína Concentrada de Suero 35% (WPC35)" },
  { code: "IN165", nombre: "Proteína Concentrada de Suero 70% (WPC70)" },
  { code: "IN166", nombre: "Proteína Concentrada de Suero 80% (WPC80)" },
  { code: "IN167", nombre: "Proteína de Arroz en Polvo" },
  { code: "IN168", nombre: "Proteína de Arveja en Polvo" },
  { code: "IN169", nombre: "Proteína Aislada de Soya (Asilada 50%)" },
  { code: "IN170", nombre: "Proteína Aislada de Soya (Aislada 70%)" },
  { code: "IN171", nombre: "Cidrón en Polvo" },
  { code: "IN172", nombre: "Glicina en Polvo (AMPES)" },
  { code: "IN173", nombre: "L-Teanina (L-Theanine) en Polvo (AMPES)" },
  { code: "IN174", nombre: "L-Triptófano" },
  { code: "IN175", nombre: "Manzanilla en Polvo" },
  { code: "IN176", nombre: "Cacao en Polvo" },
  { code: "IN177", nombre: "Canela en Polvo" },
  { code: "IN178", nombre: "Cocoa en Polvo" },
  { code: "IN179", nombre: "Limon en Polvo" },
  { code: "IN180", nombre: "Sabor Café en Polvo" },
  { code: "IN181", nombre: "Sabor Fresa en Polvo" },
  { code: "IN182", nombre: "Sabor Naranja en Polvo" },
  { code: "IN183", nombre: "Sabor Vainilla en Polvo" },
  { code: "IN184", nombre: "Aguacate en Polvo" },
  { code: "IN185", nombre: "Aguaje en Polvo (Moriche)" },
  { code: "IN186", nombre: "Asai en Polvo" },
  { code: "IN187", nombre: "Copoazú en Polvo" },
  { code: "IN188", nombre: "Fenogreco en Polvo" },
  { code: "IN189", nombre: "Levadura Nutricional" },
  { code: "IN190", nombre: "Lucuma en Polvo (IMP)" },
  { code: "IN191", nombre: "Noni en Polvo" },
  { code: "IN192", nombre: "Apio en Polvo" },
  { code: "IN193", nombre: "Pepino en Polvo" },
  { code: "IN194", nombre: "Tomate en Polvo" },
  { code: "IN195", nombre: "Zanahoria en Polvo" },
  { code: "IN196", nombre: "Alfalfa en Polvo" },
  { code: "IN197", nombre: "Alga Marina en Polvo" },
  { code: "IN198", nombre: "Chlorella en Polvo" },
  { code: "IN199", nombre: "Espinaca en Polvo" },
  { code: "IN200", nombre: "Espirulina Azul en Polvo" },
  { code: "IN201", nombre: "Espirulina Verde en Polvo" },
  { code: "IN202", nombre: "Moringa en Polvo" },
  { code: "IN203", nombre: "Musgo Marino en Polvo (Sea Moss) (AMPES)" },
  { code: "IN204", nombre: "Vitamina A" },
  { code: "IN205", nombre: "Vitamina B1 (Tiamina)" },
  { code: "IN206", nombre: "Vitamina B12 (Cobalamina)" },
  { code: "IN207", nombre: "Vitamina B2 (Riboflavina)" },
  { code: "IN208", nombre: "Vitamina B3 (Niacina)" },
  { code: "IN209", nombre: "Vitamina B5 (Ácido Pantoténico)" },
  { code: "IN210", nombre: "Vitamina B6 (Piridoxina)" },
  { code: "IN211", nombre: "Vitamina B8 (Biotina)" },
  { code: "IN212", nombre: "Vitamina B9 (Ácido Fólico)" },
  { code: "IN213", nombre: "Vitamina C (Ácido Ascórbico)" },
  { code: "IN214", nombre: "Vitamina D" },
  { code: "IN215", nombre: "Vitamina E" },
  { code: "IN216", nombre: "Vitamina K2" },
  { code: "IN217", nombre: "Vitamina K3" },
  { code: "IN218", nombre: "Passiflora en Polvo" },
  { code: "IN219", nombre: "Cúrcuma en Liquido (WOH)" },
  { code: "IN220", nombre: "Jengibre en Liquido (WOH)" },
  { code: "IN221", nombre: "Remolacha en Liquido (WOH)" },
  { code: "IN222", nombre: "Guarana en Liquido (WOH)" },
  { code: "IN223", nombre: "Espinaca en Liquido (WOH)" },
  { code: "IN224", nombre: "Limon en Liquido (WOH)" },
  { code: "IN225", nombre: "Arándano en Liquido (WOH)" },
  { code: "IN226", nombre: "Borojo en Liquido (WOH)" },
  { code: "IN227", nombre: "Azafrán en Liquido (WOH)" },
  { code: "IN228", nombre: "Chontaduro en Liquido (WOH)" },
  { code: "IN229", nombre: "Maca en Liquido (WOH)" },
  { code: "IN230", nombre: "Espirulina en Liquido (WOH)" },
  { code: "IN231", nombre: "Uva en Liquido (WOH)" },
  { code: "IN232", nombre: "Pitahaya en Liquido (WOH)" },
  { code: "IN233", nombre: "Anís en Liquido (WOH)" },
  { code: "IN234", nombre: "Menta en Liquido (WOH)" },
  { code: "IN235", nombre: "Té Verde en Liquido (WOH)" },
  { code: "IN236", nombre: "Cidrón en Liquido (WOH)" },
  { code: "IN237", nombre: "Manzanilla en Liquido (WOH)" },
  { code: "IN238", nombre: "Naranja en Liquido (WOH)" },
  { code: "IN239", nombre: "Miel en Liquido (WOH)" },
  { code: "IN240", nombre: "Apio en Liquido (WOH)" },
  { code: "IN241", nombre: "Piña en Liquido (WOH)" },
  { code: "IN242", nombre: "Zanahoria en Liquido (WOH)" },
  { code: "IN243", nombre: "Goji en Liquido (WOH)" },
  { code: "IN244", nombre: "Asai en Liquido (WOH)" },
  { code: "IN245", nombre: "Sauco en Liquido (WOH)" },
  { code: "IN246", nombre: "Moringa en Liquido (WOH)" },
  { code: "IN247", nombre: "Clorofila en Liquido (WOH)" },
  { code: "IN248", nombre: "Carboximetil Celulosa Sodica (CMC)" },
  { code: "IN249", nombre: "Ajo en Liquido (WOH)" },
  { code: "IN250", nombre: "Alcachofa en Liquido (WOH)" },
  { code: "IN251", nombre: "Aloe Vera en Liquido (WOH)" },
  { code: "IN252", nombre: "Aminoacido De Soya en Liquido (WOH)" },
  { code: "IN253", nombre: "Berenjena en Liquido (WOH)" },
  { code: "IN254", nombre: "Boldo en Liquido (WOH) (No Invimagil)" },
  { code: "IN255", nombre: "Calendula en Liquido (WOH)" },
  { code: "IN256", nombre: "Cardamomo en Liquido (WOH)" },
  { code: "IN257", nombre: "Cebolla en Liquido (WOH)" },
  { code: "IN258", nombre: "Ciruela en Liquido (WOH)" },
  { code: "IN259", nombre: "Guanabana en Liquido (WOH)" },
  { code: "IN260", nombre: "Guayaba en Liquido (WOH)" },
  { code: "IN261", nombre: "Mangostino en Liquido (WOH)" },
  { code: "IN262", nombre: "Marañon en Liquido (WOH)" },
  { code: "IN263", nombre: "Nispero en Liquido (WOH)" },
  { code: "IN264", nombre: "Noni en Liquido (WOH)" },
  { code: "IN265", nombre: "Papaya en Liquido (WOH)" },
  { code: "IN266", nombre: "Propoleo en Liquido (WOH)" },
  { code: "IN267", nombre: "Sen en Liquido (WOH) (No Invimagil)" },
  { code: "IN268", nombre: "Tilo en Liquido (WOH) (No Invimagil)" },
  { code: "IN269", nombre: "Uchuva en Liquido (WOH)" },
  { code: "IN270", nombre: "Sacha Inchi en Liquido (WOH)" },
  { code: "IN271", nombre: "Maracuyá en Liquido (WOH)" },
  { code: "IN272", nombre: "Manzana en Liquido (WOH)" },
  { code: "IN273", nombre: "Sandia en Liquido (WOH)" },
  { code: "IN274", nombre: "Coco en Liquido (WOH)" },
  { code: "IN275", nombre: "Flor de Jamaica (Hibiscus) en Liquido (WOH)" },
  { code: "IN276", nombre: "Mango en Polvo" },
  { code: "IN277", nombre: "Mango en Liquido (WOH)" },
  { code: "IN278", nombre: "Cloruro de Magnesio" },
  { code: "IN279", nombre: "Vitamina B7 (Biotina)" },
  { code: "IN280", nombre: "Proteína Texturizada de Soya" },
  { code: "IN281", nombre: "Vitamina 1 (GE)" },
  { code: "IN282", nombre: "L-Citrulina Malato" },
  { code: "IN283", nombre: "Harina de Quinua" },
  { code: "IN284", nombre: "Cebolla Roja en Polvo" },
  { code: "IN285", nombre: "Ajo en Polvo" },
  { code: "IN286", nombre: "Prebióticos, Probióticos y Postbióticos en Polvo" },
];
